### ISSUE TITLE
reproducible examples

### ISSUE THREAD

**Issue by thumbert** [vadimtsushko/ag-grid#1]
Hi, 

I was looking for a data grid for dart and found your package.  Unfortunately, I can't make the examples work because you haven't committed the dist/ folder.  I've tried to put the ag-grid js distribution directly, and I got some partial success, but I think the versions are off.  Can you provide some info on how to run the examples?

Thank you for doing this work.  It looks like a great project!

Best regards

**Comment by thumbert** [comment]
As a clarification, in example1.html I've replaced your script call with 
<script src="https://cdnjs.cloudflare.com/ajax/libs/ag-grid/10.1.0/ag-grid.js"></script>
The table outline is visible, as are the columns, but the cells are empty.  No data is displayed. 

Thank you

**Comment by vadimtsushko** [comment]
Hi
Just updated a repo, there are three presumable working examples in web root directory, also couple of examples in subdirectories file_browser and enterprise_model should work.
Old not working and / or obsolete examples left moved to the `old` subdirectory.
There is plenty of features that was implemented in the ag-grid natively in that year or so. Date column with a filtering one of these things.
